[dns_serveur]
#Serveur DNS pricipal 
dns1 ansible_host = 192.168.1.10 ansible_user=ubuntu 

[dns_client]
client1 ansible_host=192.168.1.20 ansible_use=ubuntu 
client1 ansibe_host=192.168.1.21 ansible_user=ubuntu 

[local]
localhost ansible_connection=local 

[all:vars]

ansible_python_interpreter=/usr/bin/python3
dns_domain=exemple.local 
dns_server_ip=192.168.1.10
