---
- name: Mettre à jour apt
  apt:
    update_cache: yes

- name: Installer OpenSSH server
  apt:
    name: openssh-server
    state: present

- name: Démarrer SSH
  systemd:
    name: ssh
    state: started
    enabled: yes

- name: Configurer sudo NOPASSWD pour nax
  lineinfile:
    path: /etc/sudoers
    regexp: '^nax\s+ALL='
    line: 'nax ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Autoriser SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: Vérifier connexion SSH
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    timeout: 30
